apiVersion: v1
kind: Namespace
metadata:
  name: jenkins

---
apiVersion: v1
kind: Namespace
metadata:
  name: sonarqube

---
apiVersion: v1
kind: Namespace
metadata:
  name: nexus

---
apiVersion: v1
kind: Namespace
metadata:
  name: app-test

---
apiVersion: v1
kind: Namespace
metadata:
  name: app-dev

---
apiVersion: v1
kind: Namespace
metadata:
  name: app-prod
