apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: sonaqube-ingress
  namespace: sonarqube
spec:
  virtualhost:
    fqdn: sonarqube.atostask.com
  routes:
    - conditions:
      - prefix: /
      services:
        - name: sonarqube-sonarqube
          port: 9000
