apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  namespace: nexus
spec:
  storageClassName: nexus-sc
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nexux/
david_devops_tasks@master:
