apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: jenkins-ingress
  namespace: jenkins
spec:
  virtualhost:
    fqdn: jenkins.atostask.com
  routes:
    - conditions:
      - prefix: /
      services:
        - name: jenkins 
          port: 8080
